### ISSUE TITLE
Installation using devtools fails because Rhtslib12 cannot be installed

### ISSUE THREAD

**Issue by richardstoeckl** [haizi-zh/bedtorch#2]
Hi,
Thank you for the very interesting Tool!
Sadly when I try to install it via
```R
devtools::install_github("haizi-zh/bedtorch")
```
I get an error message while the dependency Rhtslib12 is being installed:
```R
fatal: no Git-Repository: /tmp/RtmpeJ9NO8/R.INSTALLeb0655b07f9dd/Rhtslib12/src/htslib-1.12/htscodecs/../.git/modules/htscodecs
```
and
```R
/usr/bin/ld: /home/USER/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib12/usrlib/libhts.a(mFILE.o): warning: relocation against `stdout@@GLIBC_2.2.5' in read-only section `.text'
/usr/bin/ld: /home/USER/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib12/usrlib/libhts.a(hts.o): relocation R_X86_64_PC32 against symbol `seq_nt16_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:6: Rhtslib12.so] Fehler 1
ERROR: compilation failed for package ‘Rhtslib12’
* removing ‘/home/USER/R/x86_64-pc-linux-gnu-library/4.0/Rhtslib12’
Downloading GitHub repo haizi-zh/Rhtslib12@HEAD
Skipping Rhtslib12, it is already being installed
✓  checking for file ‘/tmp/RtmpJeHpiJ/remoteseaf7f27333b87/haizi-zh-bedtorch-4b0900c/DESCRIPTION’ ...
─  preparing ‘bedtorch’:
✓  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘bedtorch_0.1.8.tar.gz’
   
Installing package into ‘/home/USER/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
ERROR: dependency ‘Rhtslib12’ is not available for package ‘bedtorch’
* removing ‘/home/USER/R/x86_64-pc-linux-gnu-library/4.0/bedtorch’
Warnmeldungen:
1: In i.p(...) :
  installation of package ‘/tmp/RtmpJeHpiJ/fileeaf7f3f2b8fea/Rhtslib12_1.23.0.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/tmp/RtmpJeHpiJ/fileeaf7f1f9dc28f/bedtorch_0.1.8.tar.gz’ had non-zero exit status
```

How can I resolve this issue?
Thank you!

**Comment by haizi-zh** [comment]
Hi @richardstoeckl , thanks for your feedback. It seems there's something wrong installing one of the dependency package: Rhtslib12.

Some of bedtorch's IO features directly invoke functions of htslib (https://github.com/samtools/htslib), because I want to eliminate the dependency on external command line tools such as tabix and bgzip. Currently, there is a widely used Bioconductor package Rhtslib (https://github.com/Bioconductor/Rhtslib) which is an R wrapper over htslib. Unfortunately, it only wraps an oudated htslib version (1.7, over three years old), and some essential features from current htslib (1.2) are missing. Therefore, I forked the original Rhtslib project as Rhtslib12 (https://github.com/haizi-zh/Rhtslib12).

I'll look into this problem later today or tomorrow and figure out why your installation failed. Will get back in touch soon!

**Comment by richardstoeckl** [comment]
Thank you for your effort. If I can help by providing system information or more logs let me know!

**Comment by haizi-zh** [comment]
@richardstoeckl I've made some updates and fixed some bugs. The installation should be working. Would you try one more time?

**Comment by richardstoeckl** [comment]
Installation succeeded on two different machines and systems. Thanks for the fast response and fix!
